# Generated by Django 5.2.9 on 2026-03-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0074_authorratingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги сообщества для поиска и сортировки.', related_name='comuns_tagged', to='feeds.tag', verbose_name='Теги'),
        ),
    ]
