# Generated by Django 5.2.9 on 2026-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0079_backfill_comun_logo_from_source_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='blocked_tags',
            field=models.ManyToManyField(blank=True, help_text='Посты с этими тегами не будут попадать в сообщество.', related_name='comuns_blocked', to='feeds.tag', verbose_name='Исключенные теги'),
        ),
        migrations.AddField(
            model_name='comun',
            name='excluded_authors',
            field=models.ManyToManyField(blank=True, help_text='Авторы, чьи посты не будут попадать в это сообщество.', related_name='excluded_from_comuns', to='feeds.author', verbose_name='Исключенные авторы'),
        ),
    ]
