# Generated by Django 5.2.9 on 2026-03-24 09:28

from django.db import migrations, models


def backfill_source_tags(apps, schema_editor):
    Comun = apps.get_model('feeds', 'Comun')
    for comun in Comun.objects.exclude(product_tag_id__isnull=True).iterator():
        comun.source_tags.add(comun.product_tag_id)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0080_comun_blocked_tags_comun_excluded_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='source_tags',
            field=models.ManyToManyField(blank=True, help_text='Посты с этими тегами будут попадать в сообщество.', related_name='comuns_source', to='feeds.tag', verbose_name='Теги сообщества'),
        ),
        migrations.RunPython(backfill_source_tags, noop_reverse),
    ]
