# Generated by Django 5.2.9 on 2026-04-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0087_postratingvote_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='telegram_channel_username',
            field=models.CharField(blank=True, help_text='Публичный @username канала. Можно указать заранее на сайте, а затем завершить настройку в боте.', max_length=255, verbose_name='Username Telegram-канала'),
        ),
        migrations.AddField(
            model_name='comun',
            name='telegram_source_author',
            field=models.OneToOneField(blank=True, help_text='Если указан, новые посты этого Telegram-канала попадают в сообщество.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_source_comun', to='feeds.author', verbose_name='Telegram-канал сообщества'),
        ),
    ]
