# Generated by Django 5.2.9 on 2026-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0089_comun_glossary_enabled_comunglossaryterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='roadmap_enabled',
            field=models.BooleanField(default=True, help_text='Если включено, в сообществе будет доступна публичная дорожная карта.', verbose_name='Включить дорожную карту'),
        ),
    ]
