# Generated by Django 5.2.9 on 2026-04-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0092_backfill_toc_template_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunCustomPostTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Название шаблона")),
                ("slug", models.SlugField(max_length=160, verbose_name="Слаг шаблона")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_post_templates",
                        to="feeds.comun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользовательский шаблон сообщества",
                "verbose_name_plural": "Пользовательские шаблоны сообществ",
                "ordering": ["sort_order", "name", "id"],
                "unique_together": {("comun", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ComunCustomPostTemplateField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=160, verbose_name="Ключ поля")),
                ("label", models.CharField(max_length=120, verbose_name="Название поля")),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "Текст"), ("file", "Файл"), ("select", "Выбор значений")],
                        default="text",
                        max_length=16,
                        verbose_name="Тип поля",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[("header", "Хедер"), ("footer", "Футер")],
                        default="header",
                        max_length=16,
                        verbose_name="Расположение",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="Обязательное")),
                ("options", models.JSONField(blank=True, default=list, verbose_name="Опции выбора")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="feeds.comuncustomposttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поле пользовательского шаблона сообщества",
                "verbose_name_plural": "Поля пользовательских шаблонов сообществ",
                "ordering": ["sort_order", "id"],
                "unique_together": {("template", "key")},
            },
        ),
        migrations.CreateModel(
            name="ComunCustomPostTemplateBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("toc", "Оглавление"),
                            ("header", "Заголовок"),
                            ("list", "Список"),
                            ("image", "Изображение"),
                            ("quote", "Цитата"),
                            ("callout", "Врезка"),
                            ("author", "Автор"),
                            ("code", "Код"),
                            ("poll", "Опрос"),
                            ("divider", "Разделитель"),
                            ("spoiler", "Спойлер"),
                            ("gallery", "Галерея"),
                            ("map", "Карта"),
                            ("compare", "Сравнение изображений"),
                            ("link", "Ссылка"),
                            ("embed", "Встраивание (Embed)"),
                            ("post_link", "Ссылка на пост"),
                            ("music", "Музыка"),
                            ("movie_time", "Время в фильме"),
                            ("movie_card", "Карточка фильма"),
                            ("post_rating", "Рейтинг"),
                        ],
                        max_length=64,
                        verbose_name="Блок редактора",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("available", "Доступен в шаблоне"),
                            ("header", "Хедер"),
                            ("footer", "Футер"),
                        ],
                        default="available",
                        max_length=16,
                        verbose_name="Расположение",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="Обязательный")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_rules",
                        to="feeds.comuncustomposttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок пользовательского шаблона сообщества",
                "verbose_name_plural": "Блоки пользовательских шаблонов сообществ",
                "ordering": ["sort_order", "id"],
                "unique_together": {("template", "block_type")},
            },
        ),
    ]
