# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models


BUILTIN_TEMPLATE_LABELS = {
    "basic": "Пост",
    "movie_review": "Кинообзор",
    "post_vote_poll": "Голосование за посты",
    "music_release": "Музыкальный релиз",
}

EDITOR_BLOCK_VALUES = {
    "toc",
    "header",
    "list",
    "table",
    "image",
    "quote",
    "callout",
    "author",
    "code",
    "poll",
    "divider",
    "spoiler",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "post_link",
    "music",
    "movie_time",
    "movie_card",
    "post_rating",
}


def _normalize_allowed_templates(raw_value):
    if isinstance(raw_value, list):
        source = raw_value
    elif isinstance(raw_value, tuple):
        source = list(raw_value)
    elif isinstance(raw_value, str):
        source = [raw_value]
    else:
        source = []

    normalized = []
    seen = set()
    for item in source:
        value = str(item or "").strip().lower()
        if not value or value in seen:
            continue
        seen.add(value)
        normalized.append(value)
    if "basic" not in seen:
        normalized.insert(0, "basic")
    return normalized


def backfill_custom_post_template_configs(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    ComunCustomPostTemplate = apps.get_model("feeds", "ComunCustomPostTemplate")
    Comun = apps.get_model("feeds", "Comun")

    for template_type, label in BUILTIN_TEMPLATE_LABELS.items():
        PostTemplateConfig.objects.filter(template_type=template_type).update(label=label)

    custom_templates = (
        ComunCustomPostTemplate.objects.prefetch_related("block_rules")
        .select_related("comun")
        .all()
    )
    comun_allowed_by_id = {}

    for template in custom_templates:
        template_type = f"custom_{template.id}"
        enabled_blocks = []
        seen_blocks = set()
        for block in template.block_rules.all().order_by("sort_order", "id"):
            block_type = str(block.block_type or "").strip().lower()
            if (
                block.placement != "available"
                or block_type not in EDITOR_BLOCK_VALUES
                or block_type in seen_blocks
            ):
                continue
            seen_blocks.add(block_type)
            enabled_blocks.append(block_type)

        config = PostTemplateConfig.objects.filter(custom_template_id=template.id).first()
        if not config:
            config = PostTemplateConfig.objects.filter(template_type=template_type).first()
        if config:
            config.template_type = template_type
            config.label = template.name
            config.custom_template_id = template.id
            config.enabled_editor_blocks = enabled_blocks
            config.save(
                update_fields=[
                    "template_type",
                    "label",
                    "custom_template",
                    "enabled_editor_blocks",
                    "updated_at",
                ]
            )
        else:
            PostTemplateConfig.objects.create(
                template_type=template_type,
                label=template.name,
                custom_template_id=template.id,
                enabled_editor_blocks=enabled_blocks,
            )

        comun_id = template.comun_id
        if comun_id not in comun_allowed_by_id:
            comun_allowed_by_id[comun_id] = _normalize_allowed_templates(
                template.comun.allowed_post_templates
            )
        if template_type not in comun_allowed_by_id[comun_id]:
            comun_allowed_by_id[comun_id].append(template_type)

    for comun_id, allowed_templates in comun_allowed_by_id.items():
        Comun.objects.filter(id=comun_id).update(allowed_post_templates=allowed_templates)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0097_allow_template_body_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttemplateconfig",
            name="template_type",
            field=models.CharField(
                max_length=160,
                unique=True,
                verbose_name="Тип шаблона",
            ),
        ),
        migrations.AddField(
            model_name="posttemplateconfig",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Название, которое пользователи видят в выборе типа публикации.",
                max_length=120,
                verbose_name="Название шаблона",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posttemplateconfig",
            name="custom_template",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_template_config",
                to="feeds.comuncustomposttemplate",
                verbose_name="Пользовательский шаблон сообщества",
            ),
        ),
        migrations.RunPython(backfill_custom_post_template_configs, noop_reverse),
    ]
